# Site Specific Configuration
name: Junduo Liu
#description: A simple Jekyll theme
#url: https://example.com
#author: tajacks
#timezone: America/Toronto
#timezone_short: ET

# Keywords
keywords: ['seo', 'key', 'words']

# Analytics (Plausible requires sign-up)
analytics:
  plausible:
    enabled: false
    site_fqdn: 'your.site.fqdn'
    script_source: 'https://plausible.io/js/script.js'

# Styling
#sass:
  #sass_dir: _sass
  #style: expanded # compact, expanded or compressed

# Paginate
pagination:
  enabled: true
  # Value set low for demonstration purposes
  per_page: 3
  sort_field: 'date'
  sort_reverse: true

# Category Paginating
autopages:
  enabled: false
  categories:
    title: 'Posts in category :cat'
    permalink: '/category/:cat'
    silent: false
#films
films:
  - title: "China Jar (2019)"
    video_url: "https://vimeo.com/763648482"
    description: "An unexpected intertwinement between the struggle of a Chinese migrant worker and a restaurant owner's family drama."
    thumbnail: "/Thumbnails/ChinaJar.png"
  - title: "Fishing Nights (2021)"
    video_url: "https://vimeo.com/763715358"
    description: "A retired manâ€™s quiet life shifts when a girl selling a stone fish rekindles his sense of wonder."
    thumbnail: "/Thumbnails/FishingNights.png"
#games
games:
  - title: "A Walk Under Many Suns"
    game_url: "https://toby0001.itch.io/awalkundermanysuns"
    thumbnail: "/Thumbnails/Afterpath.png"
    description: "A point-and-click narrative game. Guide the dead to their resting place."
  - title: "Can't Get Over It"
    game_url: "https://toby0001.itch.io/cant-get-over-it"
    thumbnail: "/Thumbnails/Can't Get Over It.png"
    description: "An absurd physical 2D platform. Get different fingers and use them to climb to the top."
  - title: "Fingers"
    game_url: "https://toby0001.itch.io/fingers"
    thumbnail: "/Thumbnails/Fingers.png"
    description: "A 3D walking sim in a rich man's mansion."
  - title: "Superstitions"
    game_url: "https://toby0001.itch.io/superstitions"
    thumbnail: "/Thumbnails/Superstitions.png"
    description: "A narrative adventure set in rural China, where a policeman unravels a mystery amid belief and bureaucracy."
  - title: "Silo_Remains"
    game_url: "https://toby0001.itch.io/silo-remains"
    thumbnail: "/Thumbnails/Silo_Remains.png"
    description: "A 3D puzzle adventure. Descend into an alien silo ruled by absurd logic and hidden symbols."


photos:
  - thumbnail: "Photos/1.jpg"
  - thumbnail: "Photos/2.jpg"
  - thumbnail: "Photos/3.jpg"
  - thumbnail: "Photos/5.jpg"
  - thumbnail: "Photos/6.jpg"
  - thumbnail: "Photos/7.jpg"
  - thumbnail: "Photos/8.jpg"
  - thumbnail: "Photos/9.jpg"
  - thumbnail: "Photos/10.jpg"
  - thumbnail: "Photos/11.JPG"
  - thumbnail: "Photos/12.jpg"
  - thumbnail: "Photos/13.jpg"
  - thumbnail: "Photos/14.jpg"
  - thumbnail: "Photos/15.jpg"
  - thumbnail: "Photos/16.jpg"
  - thumbnail: "Photos/17.JPG"
  - thumbnail: "Photos/4.jpg"

# Exclusions
exclude: [ 'README.md', 'COPYING' ]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag

